Exec commands in running p4app instance (#38)
* Run a command on a MN host of a currently running p4app

* exec commands inside currently running docker container

* doc for exec

diff --git a/p4app b/p4app
--- a/p4app
+++ b/p4app
@@ -51,6 +51,7 @@ function build-command {
 function run-p4app {
   APP_TO_RUN=/tmp/app.tar.gz
   docker run --privileged --interactive --tty --rm \
+            --name "p4app_$RANDOM" \
             -v $1:$APP_TO_RUN \
             -v "$P4APP_LOGDIR":/tmp/p4app_logs \
              $P4APP_IMAGE $APP_TO_RUN "${@:2}"
@@ -122,6 +123,23 @@ function update-command {
   docker pull $P4APP_IMAGE
 }
 
+function exec-command {
+  container_id=$(docker ps | grep -m1 p4app_ | awk '{print $1}')
+
+  if [ -z "$container_id" ]; then
+      (>&2 echo "Couldn't find any p4app currently running.")
+      exit 1
+  fi
+
+  if [ -t 1 ]; then
+      # Called from a terminal, be interactive
+      docker exec -it $container_id ${@:1}
+  else
+      # Inside a pipe, don't allocate a ptty
+      docker exec $container_id ${@:1}
+  fi
+}
+
 function usage-command {
   echo "Usage:"
   echo "  p4app run <program.p4app>"
@@ -136,6 +154,8 @@ function usage-command {
   echo "      Expand a p4app file into a directory, in-place."
   echo "  p4app update"
   echo "      Update the toolchain to the newest version."
+  echo "  p4app exec <command>"
+  echo "      Execute a command on the most recent p4app instance."
   exit 1
 }
 
@@ -154,6 +174,9 @@ case "$1" in
     ;;
   "update")
     update-command "${@:2}"
+    ;;
+  "exec")
+    exec-command "${@:2}"
     ;;
   *)
     usage-command
